defaults:
  - dataset: iot_intrusion_dataset.yaml
  - evaluation: autoencoder_eval.yaml
  - _self_

training_loop_class: training_loops.autoencoder_training_loop.AutoEncoderTrainingLoop
experiment_name: test_eval
checkpoint_path: C:\Users\42spa\Programing\PythonApps\FewShotMaliciousTraffic\lightning_logs\version_8\checkpoints\epoch=49-step=3150.ckpt
batch_size: 512
num_workers: 20