defaults:
  - dataset: iot_intrusion_dataset.yaml
  - evaluation: zero_shot.yaml
  - _self_

training_loop_class: training_loops.classification_training_loop.ClassificationTrainingLoop
experiment_name: test_eval
checkpoint_path: no_such_file
batch_size: 512
num_workers: 32