defaults:
  - dataset: mqtt_dataset.yaml
  - evaluation: few_shot.yaml
  - _self_

training_loop_class: training_loops.classification_training_loop.ClassificationTrainingLoop
experiment_name: test_eval
checkpoint_path: lightning_logs\version_39\checkpoints\epoch=9-step=36210.ckpt
batch_size: 512
num_workers: 1